version: "3"

networks:
  postgres12:
    external: true

services:
  strapi:
    container_name: strapi
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: postgres12
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: ${STRAPI_DATABASE_PASSWORD}
      # https://strapi.io/documentation/3.0.0-beta.x/getting-started/troubleshooting.html#why-can-t-i-create-or-update-content-types-in-production-staging
      # NODE_ENV: production
    networks:
      - postgres12
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"
