version: "2.1"

networks:
  postgres14:
    external: true
  mayan:
    name: mayan

volumes:
  broker:
    driver: local
  app:
    driver: local
  results:
    driver: local

services:
  broker:
    container_name: mayan-broker
    image: healthcheck/rabbitmq
    # https://docs.mayan-edms.com/parts/troubleshooting/docker.html#rabbitmq-is-not-being-persisting-messages-despite-using-docker-volumes
    hostname: mayan-edms-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: mayan
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: mayan
    networks:
      - mayan
    volumes:
      - broker:/var/lib/rabbitmq
  results:
    container_name: mayan-results
    image: healthcheck/redis
    networks:
      - mayan
    volumes:
      - results:/data
  mayan:
    container_name: mayan-app
    # Pin the correct version; see the recommended image tag on https://docs.mayan-edms.com/chapters/docker/install_simple.html#docker-install
    image: mayanedms/mayanedms:s4
    depends_on:
      broker:
        condition: service_healthy
      results:
        condition: service_healthy
    networks:
      - postgres14
      - mayan
    environment:
      MAYAN_CELERY_BROKER_URL: amqp://mayan:mayan@broker:5672/mayan
      MAYAN_CELERY_RESULT_BACKEND: redis://results:6379/0
      MAYAN_DATABASE_ENGINE: django.db.backends.postgresql
      MAYAN_DATABASE_HOST: postgres14
      MAYAN_DATABASE_NAME: mayan
      MAYAN_DATABASE_USER: mayan
      MAYAN_DATABASE_PASSWORD: ${MAYAN_DATABASE_PASSWORD}
      MAYAN_APT_INSTALLS: "tesseract-ocr-deu tesseract-ocr-por tesseract-ocr-ita"
      MAYAN_DOCUMENTS_LANGUAGE: deu
      MAYAN_TIME_ZONE: Europe/Berlin
      # http://mayan:8001/#/settings/namespaces/converter/
      MAYAN_CONVERTER_ASSET_CACHE_STORAGE_BACKEND_ARGUMENTS: "{location: /var/lib/mayan_cache/converter_assets_cache}"
      # http://mayan:8001/#/settings/namespaces/documents/
      MAYAN_DOCUMENTS_CACHE_STORAGE_BACKEND_ARGUMENTS: "{location: /var/lib/mayan_cache/document_cache}"
      MAYAN_DOCUMENTS_FILE_PAGE_IMAGE_CACHE_STORAGE_BACKEND_ARGUMENTS: "{location: /var/lib/mayan_cache/document_file_page_image_cache}"
      MAYAN_DOCUMENTS_VERSION_PAGE_IMAGE_CACHE_STORAGE_BACKEND_ARGUMENTS: "{location: /var/lib/mayan_cache/document_version_page_image_cache}"
      # http://mayan:8001/#/settings/namespaces/sources/
      MAYAN_SOURCES_CACHE_STORAGE_BACKEND_ARGUMENTS: "{location: /var/lib/mayan_cache/source_cache}"
      # http://mayan:8001/#/settings/namespaces/document_states/
      MAYAN_WORKFLOWS_IMAGE_CACHE_STORAGE_BACKEND_ARGUMENTS : "{location: /var/lib/mayan_cache/workflows}"
      # http://mayan:8001/#/settings/namespaces/search/
      # The Whoosh backend is not returning any results
      MAYAN_SEARCH_BACKEND: "mayan.apps.dynamic_search.backends.django.DjangoSearchBackend"
    ports:
      - "8001:8000"
    volumes:
      - ~/Library/Caches/mayan:/var/lib/mayan_cache
      # Change the database on YAML files in this dir with:
      # rg postgres14 ~/OneDrive/Apps/mayan/ -l | xargs code
      - ~/OneDrive/Apps/mayan/lib:/var/lib/mayan
      - ~/OneDrive/Apps/mayan/watch:/srv/watch
      - ~/OneDrive/Documents/Mayan_Staging:/srv/staging
