version: "3.5"

networks:
  postgres14:
    external: true

services:
  wikijs:
    container_name: wikijs
    # Using canary version that contains this fix: https://github.com/Requarks/wiki/issues/4559
    image: requarks/wiki:canary
    # Revert to version 2 once there is a new release: https://github.com/Requarks/wiki/releases
    # image: requarks/wiki:2
    networks:
      - postgres14
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres14
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: ${WIKIJS_PASSWORD}
      DB_NAME: wikijs
    ports:
      - "8004:3000"
