version: "3.5"

# https://docs.docker.com/compose/compose-file/#volume-configuration-reference
# https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  # TODO: fix: Redmine is the last one using PostgreSQL 12; remove these lines when it's upgraded to PostgreSQL 14
  # postgres12:
  #   driver: local
  #   name: postgres12
  postgres14:
    driver: local
    name: postgres14

networks:
  # TODO: fix: Redmine is the last one using PostgreSQL 12; remove these lines when it's upgraded to PostgreSQL 14
  # postgres12:
  #   name: postgres12
  postgres14:
    name: postgres14

# https://registry.hub.docker.com/_/postgres
services:
  # TODO: fix: Redmine is the last one using PostgreSQL 12; remove these lines when it's upgraded to PostgreSQL 14
  # postgres12:
  #   image: postgres:12
  #   restart: unless-stopped
  #   container_name: postgres12
  #   # Those are also the default values, left here for clarity. This will be the superuser.
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   # https://docs.docker.com/compose/compose-file/#/expose
  #   expose:
  #     - "5432"
  #   # https://docs.docker.com/compose/compose-file/#/ports
  #   ports:
  #     - "7712:5432"
  #   # Use a separate volume that is persisted even if the container is deleted
  #   volumes:
  #     - postgres12:/var/lib/postgresql/data
  #     - ~/OneDrive/Backup:/var/backups/
  #   networks:
  #     - postgres12

  postgres14:
    image: postgres:16
    restart: unless-stopped
    container_name: postgres14
    # Those are also the default values, left here for clarity. This will be the superuser.
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # https://postgresqlco.nf/doc/en/param/max_connections/
    # https://postgresqlco.nf/doc/en/param/shared_buffers/
    command: postgres -c max_connections=150 -c shared_buffers=256MB
    # https://docs.docker.com/compose/compose-file/#/expose
    expose:
      - "5432"
    # https://docs.docker.com/compose/compose-file/#/ports
    ports:
      - "7714:5432"
    # Use a separate volume that is persisted even if the container is deleted
    volumes:
      - postgres14:/var/lib/postgresql/data
      - ~/OneDrive/Backup:/var/backups/
    networks:
      - postgres14
